name = "admin"
version = "1.0.0"
target = "javascript"
# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "", repo = "" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
lustre = ">= 5.0.1 and < 6.0.0"
gleam_stdlib = ">= 0.60.0 and < 1.0.0"
plinth = ">= 0.6.0 and < 1.0.0"
grille_pain = ">= 1.1.4 and < 2.0.0"
gleam_javascript = ">= 1.0.0 and < 2.0.0"
formal = ">= 2.2.0 and < 3.0.0"
sketch_lustre = ">= 3.1.1 and < 4.0.0"
sketch = ">= 4.1.0 and < 5.0.0"
gleam_json = ">= 3.0.1 and < 4.0.0"


