
direction: left

**: {
    style.font-size: 100
    vertical-gap: 50
    style.font-color: "#fffafa"
} 


  
الكلام  {
    grid-columns: 1
    width: 3400
  اللفظ \: صوت مشتمل على حروف الهجاء :{width: 3300}
  المركب \: مؤلف من كلمتين أو أكثر تحقيقا أو تقديرا
  المفيد \: يحسن سكوت المتكلم عليه ويحصل منه الفائدة
  بالوضع  \: لفظ وضعته العرب للدلالة على معنى من المعاني
} 
أنواع الكلام  {
    grid-columns: 1 
     
   اسم \: كلمة دلت على معنى في نفسها ولم تقترن بزمان :{width: 3300} 
 
   فعل \: كلمة دلت على معنى في نفسها واقترنت بزمان 

   حرف \: كلمة لا تدل على معنى في نفسها وتدل على معنى في غيرها

}
علامات الاسم: {
    grid-columns: 1
     
 الإسناد إليه - كتبت بالقلم  ( التاء فاعل و مسند اليها الكتابة ) :{width: 3300}
 الخفض - رأيت كتاب الطالبِ ( طالب اسم لأنه مخفوض ) 
 حروف الخفض - عدت إلى المنزلِ ( منزل اسم لأنه سبق بحرف خفض ) 
 التنوين - هذا طالبٌ مجتهدٌ ( طالب و مجتهد اسمان لأنهما منونان ) 
 دخول الألف واللام - كتبت على الطاولة ( طاولة اسم لدخول أل عليها ) 
}

علامات الفعل : {
    grid-columns: 1
    
    
     قد - قد أفلح المؤمنون  ( أفلح فعل لدخول قد عليه ) :{width: 3300}
     السين - مثال 
     سوف - مثال ثاني
    تاء التأنيث الساكنة - مثال
    }