
direction: left

*: {
    style.font-size: 100

} 



الكلام -> اللفظ -> صوت مشتمل على حروف الهجاء
الكلام -> المركب -> مؤلف من كلمتين أو أكثر تحقيقا أو تقديرا
الكلام -> المفيد -> يحسن سكوت المتكلم عليه ويحصل منه الفائدة
الكلام -> بالوضع ->  لفظ وضعته العرب للدلالة على معنى من المعاني

انواع الكلام -> اسمٌ
انواع الكلام -> فعلٌ
انواع الكلام -> أمرٌ

اسمٌ -> كلمة دلت على معنى في نفسها ولم تقترن بزمان
فعلٌ -> كلمة دلت على معنى في نفسها واقترنت بزمان  
أمرٌ -> ما دل على امر يطلب حصوله بعد زمان التكلم 





علامات الاسم -> الإسناد إليه -> كتبت بالقلم  ( التاء فاعل و مسند اليها الكتابة ) 
علامات الاسم -> الخفض -> رأيت كتاب الطالبِ ( الطالب اسم لأنه مخفوض ) 
علامات الاسم -> حروف الخفض -> عدت إلى المنزلِ ( المنزل اسم لأنه سبق بحرف خفض ) 
علامات الاسم -> التنوين-> هذا طالبٌ مجتهدٌ ( طالب و مجتهد اسمان لأنهما منونان ) 
علامات الاسم -> دخول الالف واللام 




علامات الفعل -> قد
علامات الفعل -> السين
علامات الفعل -> سوف
علامات الفعل -> تاء التأنيث الساكنة


علامة الحرف -> ما لا يصلح معه دليل الاسم ولا دليل الفعل 


 



أنواع الأفعال وعلاماتها-> ماضي
أنواع الأفعال وعلاماتها-> مضارع
أنواع الأفعال وعلاماتها-> أمر

ماضي -> تاء  التأنيث الساكنة 

مضارع -> قبوله الجزم بـ لم
مضارع -> يبدأ بأحد حروف أنيت
مضارع -> يضم أوله إذا كان ماضيه من 4 حروف
مضارع -> يفتح أوله فيما عدا ذلك


أمر->  يدل على الطلب
أمر->  ياء المخاطبة
