direction: right
الكلام -> اللفظ -> المنطوق باللسان
الكلام -> المركب -> من كلمتين أو أكثر تقديرا أو تحقيقا
الكلام -> المفيد -> فائدة يحسن السكوت عليها
الكلام -> بالوضع -> المستقرئ من كلام العرب




أقسام الكلام -> حرف -> ما لا يصلح معه دليل الاسم ولا دليل الفعل
أقسام الكلام -> فعل 
أقسام الكلام  -> اسم


فعل -> قد
فعل -> السين
فعل -> سوف
فعل -> تاء التأنيث الساكنة

اسم -> الإسناد إليه
اسم -> الخفض
اسم -> حروف الخفض
اسم -> التنوين
اسم -> دخول الالف واللام


أنواع الأفعال-> أمر
أمر->  على الطلب
أمر->  ياء المخاطبة

أنواع الأفعال-> مضارع
مضارع -> قبوله الجزم بـ لم
مضارع -> يبدأ بأحد حروف أنيت
مضارع -> يضم أوله إذا كان ماضيه من 4 حروف
مضارع -> يفتح أوله فيما عدا ذلك

أنواع الأفعال-> ماضي -> ًتاء التأنيث الساكنة


*: {
    style.font-size: 55
 
}
